// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArgTUlLyYZTNjVNYTtEG7-AUtPAJ0nM0s',
    appId: '1:1067952255007:web:a4f66a27e515e77e5ea52a',
    messagingSenderId: '1067952255007',
    projectId: 'mohamoon-f35de',
    authDomain: 'mohamoon-f35de.firebaseapp.com',
    storageBucket: 'mohamoon-f35de.appspot.com',
    measurementId: 'G-7244E53MB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3dZHbHgy_nr20C1vIFC3C1sjNf6yLk8o',
    appId: '1:1067952255007:android:33746bde9062fad05ea52a',
    messagingSenderId: '1067952255007',
    projectId: 'mohamoon-f35de',
    storageBucket: 'mohamoon-f35de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyKnxuFSNi7Yyx5EOlCUIuXsOQLeifvMg',
    appId: '1:1067952255007:ios:285a09127a18234f5ea52a',
    messagingSenderId: '1067952255007',
    projectId: 'mohamoon-f35de',
    storageBucket: 'mohamoon-f35de.appspot.com',
    iosClientId: '1067952255007-bav4fotmacu87o5ico43lc8tsnmt0mbm.apps.googleusercontent.com',
    iosBundleId: 'ae.smartlink.clientmohamoon.clientMohamoon',
  );
}
